version: "3.7"
services:
  mysql:
    image: mysql:5.7.33
    environment:
      - MYSQL_ROOT_PASSWORD=password
    expose:
      - "3306"
    volumes:
      - ./runtime/mysql:/docker-entrypoint-initdb.d:ro

  presto:
    build:
      context: ./image
      args:
        - MAVEN_OPTS=${MAVEN_OPTS}
    command: ["/opt/presto/bin/launcher", "run"]
    depends_on:
      - mysql
      - hive
      - datanode
      - namenode
    ports:
      - "8080:8080"

  namenode:
    build:
      context: ./image
      args:
        - MAVEN_OPTS=${MAVEN_OPTS}
    volumes:
      - ./data/:/data/:ro
    ports:
      - "9870:9870"
      - "8020:8020"
    command: ["hdfs", "namenode"]

  datanode:
    build:
      context: ./image
      args:
        - MAVEN_OPTS=${MAVEN_OPTS}
    depends_on:
      - namenode
    ports:
      - "9864:9864"
      - "9866:9866"
      - "9867:9867"
      - "46759:46759"
    command: ["hdfs", "datanode"]

  hive:
    build:
      context: ./image
      args:
        - MAVEN_OPTS=${MAVEN_OPTS}
    depends_on:
      - mysql
      - namenode
      - datanode
    ports:
      - "9083:9083"
    command: ["/scripts/hive-entrypoint.sh"]
